# IBM Applied AI with Deep Learning Course
Taken November 2018 

### The following will be how to use pytorch a rising deep learning framework

In [1]:
import torch

In [2]:
!ls -lt

total 307
-rw-r--r-- 1 My LENOVO 197121   5775 Nov 16 20:48 intro_pytorch.ipynb
drwxr-xr-x 1 My LENOVO 197121      0 Nov  9 22:28 Deep_learning_2018
-rw-r--r-- 1 My LENOVO 197121  45108 Jun 16 16:41 wk1ICL_mean_cov.ipynb
-rw-r--r-- 1 My LENOVO 197121  20429 Jun  6 06:51 imperial_college_wk4.ipynb
-rw-r--r-- 1 My LENOVO 197121  18113 Jun  6 06:41 imperial_college_wk2.ipynb
-rw-r--r-- 1 My LENOVO 197121  18848 Jun  6 06:31 imperial_college_wk1.ipynb
-rw-r--r-- 1 My LENOVO 197121 155062 Jun  4 21:06 multivariate_chain_rule.pdf
drwxr-xr-x 1 My LENOVO 197121      0 Mar  3  2018 Old
drwxr-xr-x 1 My LENOVO 197121      0 Jan 10  2018 w4 Neural Nets
drwxr-xr-x 1 My LENOVO 197121      0 Dec  2  2017 Assignment
-rw-r--r-- 1 My LENOVO 197121    162 Oct 23  2017 ~$M Exercise.docx
-rw-r--r-- 1 My LENOVO 197121    162 Jul  3  2017 ~$tave commands.docx
drwxr-xr-x 1 My LENOVO 197121      0 Jun  7  2017 Week 2
-rw-r--r-- 1 My LENOVO 197121     45 May 27  2017 desktop.ini
drwxr-xr-x 1 My LENOVO 197121   

In [3]:
import torch.autograd as autograd
from torch import nn
from torch import optim

torch.manual_seed(123) #always good to seed before initialiser

### Creating Tensors

In [4]:
#create a torch.tensor object from python list
v = [1,2,3]
print(type(v))
v_tensor = torch.Tensor(v)
print(v_tensor)

<class 'list'>
tensor([1., 2., 3.])


In [5]:
##create a torch.Tensor object of size 2x3 from 2x3 matrix
m2x3 = [[1,2,3],[2,4,9]]
m2x3_tensor = torch.Tensor(m2x3)
print(m2x3_tensor)

tensor([[1., 2., 3.],
        [2., 4., 9.]])


In [7]:
##create a 3-d torch.Tensor object of size 3x3x3
m3x3x3 = [[[1,2,3],[4,5,6],[7,8,9]],
          [[1,2,9],[16,25,36],[49,64,81]],
         [[1,8,27],[64,125,216],[343,512,729]]]
m3x3x3_tensor = torch.Tensor(m3x3x3)
print(m3x3x3_tensor)

tensor([[[  1.,   2.,   3.],
         [  4.,   5.,   6.],
         [  7.,   8.,   9.]],

        [[  1.,   2.,   9.],
         [ 16.,  25.,  36.],
         [ 49.,  64.,  81.]],

        [[  1.,   8.,  27.],
         [ 64., 125., 216.],
         [343., 512., 729.]]])


In [8]:
print(m3x3x3_tensor[0]) ##index the 1st element 

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])


## Mathematical Operation with Tensors

In [4]:
x = torch.Tensor([2,2,2])
y = torch.Tensor([2,3,4])

#matrix multiplication 
v = torch.matmul(x,y)
print(v)

tensor(18.)


In [12]:
##concatenation 
x_1 = torch.randn(2,3)
print(x_1)
y_1 = torch.randn(2,3)
print(y_1)

tensor([[ 1.3251, -0.7990,  0.6292],
        [-1.2097, -2.1362, -0.1212]])
tensor([[-0.1443,  0.9969,  0.5697],
        [-0.4930,  0.3155, -0.2275]])


In [13]:
z1 = torch.cat((x_1,y_1),1)  #concat along column axis
print(z1)

tensor([[ 1.3251, -0.7990,  0.6292, -0.1443,  0.9969,  0.5697],
        [-1.2097, -2.1362, -0.1212, -0.4930,  0.3155, -0.2275]])


### Reshape tensors

In [14]:
x = torch.randn(64000,3,28,28) #64K images, 3 rgb channels, image dims = 28x28
##how many batches can we construct out of these images
x_reshaped = x.view(32,-1,3,28,28)  #batch_size=32, pytorch will automaticcally infer the dimension 

In [15]:
print(x_reshaped.shape)

torch.Size([32, 2000, 3, 28, 28])


## Computation Graph and Automatic Differentiation 

A computation graph is a speficication of what parameters with which connections are involveed int eh computation to give the output. Unlike tensorflow, pytorch's computational graph can be changed during run-time, is more flexible. 

In [16]:
#variables wrap tensor objects
x = autograd.Variable(torch.Tensor([1,2,3]), requires_grad=True) #takes arguments:  dataset and partial differentiation 
##access the data with 'data' attribute
print(x.data)

tensor([1., 2., 3.])


In [18]:
y = autograd.Variable(torch.Tensor([4,5,6]),requires_grad=True)
z= x+y
print(z.data)

tensor([5., 7., 9.])


In [19]:
##we can also see how z was created using grad_fn (i.e. function that created z )
operation = z.grad_fn   #z was created by element-wiseaddition (Addbackward) operation 
print(operation )

In [20]:
s = z.sum()
print(s)
print(s.grad_fn)  #s was the sum of z elements

tensor(21., grad_fn=<SumBackward0>)


#### so pytorch can track how every variable was created

In [24]:
s.backward(retain_graph=True) #backward will start backprop from this point

In [25]:
print(x)
print(x.grad)  ##partial differentiation wrt to each element in x 
print(y.grad)
##each time backward is call the gradient will accumulate

tensor([1., 2., 3.], requires_grad=True)
tensor([2., 2., 2.])
tensor([2., 2., 2.])


In [26]:
s.backward(retain_graph=True) #backward will start backprop from this point
print(x)
print(x.grad)  ##partial differentiation wrt to each element in x 
print(y.grad)
##each time backward is call the gradient will accumulate

tensor([1., 2., 3.], requires_grad=True)
tensor([3., 3., 3.])
tensor([3., 3., 3.])


In [27]:
var_x = autograd.Variable(x,requires_grad=True)
var_y = autograd.Variable(y,requires_grad=True)
#since var_z is addtion of two tensors thats enough to compute gradients
var_z = var_x+var_y
print(var_z.grad_fn)

In [30]:
new_var_z = var_z.data ##only data is passed 
print(new_var_z.grad_fn)b

None


## CUDA 

Check wether GPU acceleration is available cuda is available

In [35]:
torch.cuda.is_available()

False

In [36]:
if torch.cuda.is_available():
    ##create a LongTensor and transfer it GPU
    a = torch.LongTensor(10).fill(3).cuda()
    print(a)
    b = a.cpu()  #transfers it back to cpu

## Linear Model in Pytorch 

In [37]:
import numpy as np 
from torch.autograd import Variable  ##main building block of pyutorch 

In [39]:
x = [i for i in range(20)]
x_train=np.asarray(x, dtype=np.float32)
x_train = x_train.reshape(-1,1)  #flatten
print(x)
print(x_train.shape)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
(20, 1)


In [ ]:
y = [(5*i +2) for i in x]
y_train = np.array(y,dtype=np.float32)
y_train=y_train.reshape(-1,1)
print(y_train)
print(y_train.shape)

## Create Model Class
Every model in pytorch has to be created in a class (i.e. the blueprint or template )

In [47]:
class LinearRegressor(nn.Module):  #we're inheriting from the nn module of pytorch 
    def __init__(self,input_dim,output_dim):
        super(LinearRegressor, self).__init__()
        self.linear = nn.Linear(input_dim,output_dim)
    
    def forward(self,x):  #x is the data 
        out = self.linear(x)
        return out
    
input_dim = 1  #one column vector with 20 elements
output_dim = 1

model= LinearRegressor(input_dim, output_dim)
model
    

LinearRegressor(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)

## Loss andn Optimizer

In [50]:
loss_function = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.001)

In [54]:
epochs = 500
for epoch in range(epochs):
    epoch+=1
    ##convert inputs and outputs to torch variable
    inputs = Variable(torch.from_numpy(x_train))
    real_outputs = Variable(torch.from_numpy(y_train))
    
    #reset gradients
    optimizer.zero_grad()
    
    #forward pass - compute the output
    pred_outputs = model(inputs)
    
    ## compute loss:  how close are the predictions to true values 
    loss = loss_function(pred_outputs,real_outputs)
    
    ##backward pass -  compute the gradients
    loss.backward()
    ##update the parameters in a way that [hopefully] minimise the loss
    optimizer.step()
    
    print('epoch{}, loss{}'.format(epoch, loss.data[0]))

c:\program files\python36\lib\site-packages\ipykernel_launcher.py:22: UserWarning: invalid index of a 0-dim tensor. This will be an error in PyTorch 0.5. Use tensor.item() to convert a 0-dim tensor to a Python number


epoch1, loss3776.293212890625
epoch2, loss2133.56787109375
epoch3, loss1205.7474365234375
epoch4, loss681.7088623046875
epoch5, loss385.72833251953125
epoch6, loss218.55621337890625
epoch7, loss124.13571166992188
epoch8, loss70.805908203125
epoch9, loss40.684104919433594
epoch10, loss23.67044448852539
epoch11, loss14.06031322479248
epoch12, loss8.63171672821045
epoch13, loss5.5648698806762695
epoch14, loss3.831963539123535
epoch15, loss2.852477788925171
epoch16, loss2.298516273498535
epoch17, loss1.9849095344543457
epoch18, loss1.8070428371429443
epoch19, loss1.7058515548706055
epoch20, loss1.6479631662368774
epoch21, loss1.6145336627960205
epoch22, loss1.5949229001998901
epoch23, loss1.5831143856048584
epoch24, loss1.5757156610488892
epoch25, loss1.5708060264587402
epoch26, loss1.5673060417175293
epoch27, loss1.5646004676818848
epoch28, loss1.5623441934585571
epoch29, loss1.5603443384170532
epoch30, loss1.55849027633667
epoch31, loss1.5567162036895752
epoch32, loss1.5549908876419067
e

epoch295, loss1.1732573509216309
epoch296, loss1.1720002889633179
epoch297, loss1.170747995376587
epoch298, loss1.1694941520690918
epoch299, loss1.1682419776916504
epoch300, loss1.1669942140579224
epoch301, loss1.1657447814941406
epoch302, loss1.1644971370697021
epoch303, loss1.1632481813430786
epoch304, loss1.1620036363601685
epoch305, loss1.1607613563537598
epoch306, loss1.1595184803009033
epoch307, loss1.1582765579223633
epoch308, loss1.157037377357483
epoch309, loss1.1557985544204712
epoch310, loss1.154563307762146
epoch311, loss1.1533268690109253
epoch312, loss1.1520922183990479
epoch313, loss1.1508580446243286
epoch314, loss1.1496262550354004
epoch315, loss1.1483954191207886
epoch316, loss1.1471666097640991
epoch317, loss1.1459401845932007
epoch318, loss1.1447142362594604
epoch319, loss1.143490195274353
epoch320, loss1.142264485359192
epoch321, loss1.141042947769165
epoch322, loss1.1398208141326904
epoch323, loss1.138599157333374
epoch324, loss1.1373831033706665
epoch325, loss1.1

# Week 3: Autoencoder LSTM Anamoly Detector in keras

### this lesson may be done on the ibmWatson cloud 

In [55]:
import numpy as np
from numpy import concatenate
from matplotlib import pyplot
from pandas import read_csv
from pandas import DataFrame
from pandas import concat
import sklearn
from  sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import mean_squared_error
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.callbacks import Callback
from keras.models import Sequential
from keras.layers import LSTM, Dense, Activation
import pickle
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import ibmiotf.application
from queue import Queue
%matplotlib inline

Using TensorFlow backend.


ModuleNotFoundError: No module named 'ibmiotf'

In [57]:
!pip install ibmiotf

  Running setup.py bdist_wheel for ibmiotf: started
  Running setup.py bdist_wheel for ibmiotf: finished with status 'done'
  Stored in directory: C:\Users\My LENOVO\AppData\Local\pip\Cache\wheels\ea\fe\e0\855ec0be95b6ae2d7824e99ff5a7a0bca357b8d5807197c894
  Running setup.py bdist_wheel for paho-mqtt: started
  Running setup.py bdist_wheel for paho-mqtt: finished with status 'done'
  Stored in directory: C:\Users\My LENOVO\AppData\Local\pip\Cache\wheels\82\e5\de\d90d0f397648a1b58ffeea1b5742ac8c77f71fd43b550fa5a5
Successfully built ibmiotf paho-mqtt


Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\program files\\python36\\Lib\\site-packages\\iso8601'
Consider using the `--user` option or check the permissions.



'--user' is not recognized as an internal or external command,
operable program or batch file.


In [ ]:
!wget https://raw.githubusercontent.com/romeokienzler/developerWorks/master/lorenzattractor/watsoniotp.healthy.phase_aligned.pickle
!wget https://raw.githubusercontent.com/romeokienzler/developerWorks/master/lorenzattractor/watsoniotp.broken.phase_aligned.pickle