June 17 2019
Owner: Rhondene Wint
## Summer of AI Lesson 0 : Very Basic Pytorch syntax

Objective:
- Use this course as incentive to learn Pytorch. I already know keras but it's good to have variety because different frameworks have different advantages

<h3> what to expect in this notebook: </h3>:
- Make tensors
- Fundamental mathematical operations with tensors

<h3> What is AI </h3>
- AI means a computer program was used to make decisions. These are are rule-based systems   

- Machine Learning =  Data +Models +Features. Deep learning is a subset of Machine learning.   
- This course will focus mainly on supervised classification/regression and sequence prediction tasks.   
-  pytorch 1.1.0 was installed

In [2]:
import torch

## Manipulating Tensors (Matrices)

In [3]:
### generate a 1-dim tensor of 10 random numbers
torch.rand(10)

tensor([0.4201, 0.1353, 0.1038, 0.6211, 0.8176, 0.9199, 0.0362, 0.5701, 0.2380,
        0.8637])

In [4]:
##Create two 2x2 matrix
a = torch.rand(2,2)
b = torch.rand(2,2)

In [6]:
print(a);print(b)

tensor([[0.5894, 0.5733],
        [0.5751, 0.6806]])
tensor([[0.5181, 0.7305],
        [0.7496, 0.2736]])


In [12]:
#get the shape of the tensors
a.shape

torch.Size([2, 2])

In [7]:
a+b

tensor([[1.1074, 1.3039],
        [1.3246, 0.9542]])

In [8]:
##elementwise multiplication 
a*b

tensor([[0.3053, 0.4188],
        [0.4310, 0.1862]])

In [9]:
##matrix multiplication - two ways
print(a@b)
print(torch.mm(a,b))

tensor([[0.7351, 0.5874],
        [0.8081, 0.6063]])
tensor([[0.7351, 0.5874],
        [0.8081, 0.6063]])


In [11]:
##concatenate two tensors
torch.cat( (a,b) )

tensor([[0.5894, 0.5733],
        [0.5751, 0.6806],
        [0.5181, 0.7305],
        [0.7496, 0.2736]])

In [16]:
##create a tensor with known values
c = torch.tensor([1.5, 2.2, 0.9, 1.1])
c.shape

torch.Size([4])

In [17]:
##reshape c to a 2x2 tensor
c.view(2,2)

tensor([[1.5000, 2.2000],
        [0.9000, 1.1000]])

In [18]:
c.view(4,-1)  #-1 means as many rows as need

tensor([[1.5000],
        [2.2000],
        [0.9000],
        [1.1000]])

In [23]:
##make a 3x3 tensor filled with zeros
a = torch.zeros(3,3)
##make a 3x3 tensor filled with ones
b =  torch.ones(3,3)

##concat a and b to make a 3x6 matrix
c = torch.cat((a,b)).view(3,6)
print( 'a:',a)
print('b:', b)
print('c:', c)

a: tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
b: tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
c: tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])


In [25]:
##print the type of c
print('type of c: ', c.type())
##make a new tensor from c that is a long tensor
d = c.long()
print('d:', d.type())

type of c:  torch.FloatTensor
d: torch.LongTensor


- Make a new 3x100x100 tensor "d" filled with random values, and print the result
- <b>NOTE</b>:This is how PyTorch represents images: channels x height x width

In [27]:
d= torch.rand(3,100,100)
d

tensor([[[5.5149e-01, 9.6906e-02, 1.4303e-02,  ..., 1.4384e-01,
          3.1616e-01, 4.5295e-01],
         [2.7136e-01, 2.6205e-01, 6.9838e-01,  ..., 8.6482e-01,
          3.2670e-01, 6.0878e-01],
         [5.1833e-02, 3.7344e-01, 6.1348e-01,  ..., 9.1306e-01,
          5.7851e-01, 8.0208e-01],
         ...,
         [5.4280e-01, 2.1227e-01, 9.3819e-02,  ..., 5.5981e-02,
          2.0608e-01, 5.3967e-01],
         [2.2828e-01, 9.7704e-01, 8.5318e-01,  ..., 6.3414e-01,
          8.8972e-01, 9.0446e-01],
         [3.6411e-02, 1.8321e-01, 8.7129e-01,  ..., 6.7759e-01,
          1.7641e-01, 3.9841e-01]],

        [[8.3937e-01, 1.7552e-01, 3.0903e-01,  ..., 4.3470e-04,
          9.8597e-01, 9.1177e-01],
         [6.6056e-01, 7.3848e-01, 6.5176e-01,  ..., 8.9059e-01,
          2.8838e-01, 8.5374e-01],
         [8.7836e-01, 9.1654e-02, 3.0236e-01,  ..., 1.6041e-01,
          8.2566e-01, 4.7809e-01],
         ...,
         [1.4144e-01, 3.7353e-01, 9.4762e-01,  ..., 2.6755e-01,
          8.804

In [28]:
##print the mean and standard deviation of tensor d
print('mean of tensor d: ',d.mean())
print('standard deviation of d: ', d.std())

mean of tensor d:  tensor(0.5005)
standard deviation of d:  tensor(0.2898)
